### ISSUE TITLE
Mirror to Gitea

### ISSUE THREAD

**Issue by hello-smile6** [life00/awecron#2]
Could you set up a mirror on https://gitea.9pfs.repl.co/ ?

**Comment by life00** [comment]
Sure, but if there was a reason. I am fine with github and also the project is already on its final stage because of minimal amount of code even though it took me few weeks. If I am not mistaking MIT license allows to create a mirror, so you can.

**Comment by hello-smile6** [comment]
I'd just like to have a mirror without it under my username, and I'd prefer not to steal your username, because you might create an account later.

**Comment by life00** [comment]
Why not contribute here? And its fine if you would create it under your username, it would be like a fork, just leave a note to original repo. I was thinking of hosting my projects on different platforms but I am already used to github and at the moment I don't have any problems with it also the other reason is because more people use github that results in more activity.

**Comment by hello-smile6** [comment]
https://giveupgithub.org/
Also, okay. I'll create a mirror on my account.

**Comment by hello-smile6** [comment]
https://gitea.9pfs.repl.co/9pfs/life00-awecron

**Comment by life00** [comment]
ok great, i will add that to readme later. i am planning to move to codeberg some day though.

**Comment by hello-smile6** [comment]
> ok great, i will add that to readme later. i am planning to move to codeberg some day though.

**Self-host**. Don't use other companies' junk.

**Comment by life00** [comment]
I have a friend that allows me to host my projects on his self-hosted Forgejo.
In case there will be a need I will consider making a mirror or completely switching. Currently there is no need for that.
Closing as complete.
