### ISSUE TITLE
Settings persist between jobs

### ISSUE THREAD

**Issue by kurahaupo** [life00/awecron#5]
This line
```
                source "$i/config"
```
reads settings into the current shell. Anything that's not set will retain whatever settings were applied by the previous job.

Perhaps run each job in a new subshell?

**Comment by life00** [comment]
yeah that could be a problem if not configured properly.
i am not sure what you mean by subshell

**Comment by life00** [comment]
also i would like to add to further suggestions about fixing possible issues because of misconfiguration and other non code specific bugs. maybe this would sound dumb but i dont want to increase the amount of code in `awecron` file to create error detection (not prevention) because i want the code to be as minimal as possible. I could though create another bash script that would be called `debugger` and would look for non code specific bugs like: permissions, missing files, missing configuration variables, etc.

**Comment by life00** [comment]
also i think it is possible to make "modular features" that would be bash scripts in different files that add any functionality to the cron and can be easily removed if not in use

**Comment by kurahaupo** [comment]
> i am not sure what you mean by subshell

A sub-shell is a separate process created by putting `(` and `)` around a group of commands. Any changes to the shell context within that process won't affect the outer process; in particular that means that setting variables, changing directory, opening & closing filedescriptors, or setting the umask will be independent of the main process.

**Comment by kurahaupo** [comment]
An alternative - and in this case probably preferable - approach would simply be to set some default values (possibly "unset") before sourcing the file, so that anything that's not set will have a predictable value rather than a random one from the previous command invocation.

**Comment by life00** [comment]
This was implemented.
Closing.
